/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Condition = IDL.Variant({
  'good' : IDL.Null,
  'mint' : IDL.Null,
  'poor' : IDL.Null,
  'nearMint' : IDL.Null,
  'excellent' : IDL.Null,
});
export const PriceCents = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ListingId = IDL.Nat;
export const Listing = IDL.Record({
  'id' : ListingId,
  'cardName' : IDL.Text,
  'isSold' : IDL.Bool,
  'seller' : IDL.Principal,
  'image' : ExternalBlob,
  'cardSet' : IDL.Text,
  'priceCents' : PriceCents,
  'sellerUsername' : IDL.Text,
  'condition' : Condition,
});
export const Username = IDL.Text;
export const UserProfile = IDL.Record({ 'username' : Username });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, Condition, PriceCents, ExternalBlob],
      [ListingId],
      [],
    ),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getBrowseFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getInterestedBuyers' : IDL.Func(
      [ListingId],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getMyInterests' : IDL.Func([], [IDL.Vec(ListingId)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isListingSwipedByCaller' : IDL.Func([ListingId], [IDL.Bool], ['query']),
  'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'markListingAsSold' : IDL.Func([ListingId], [], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'resetUsers' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'swipeRightOnListing' : IDL.Func([ListingId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Condition = IDL.Variant({
    'good' : IDL.Null,
    'mint' : IDL.Null,
    'poor' : IDL.Null,
    'nearMint' : IDL.Null,
    'excellent' : IDL.Null,
  });
  const PriceCents = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ListingId = IDL.Nat;
  const Listing = IDL.Record({
    'id' : ListingId,
    'cardName' : IDL.Text,
    'isSold' : IDL.Bool,
    'seller' : IDL.Principal,
    'image' : ExternalBlob,
    'cardSet' : IDL.Text,
    'priceCents' : PriceCents,
    'sellerUsername' : IDL.Text,
    'condition' : Condition,
  });
  const Username = IDL.Text;
  const UserProfile = IDL.Record({ 'username' : Username });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, Condition, PriceCents, ExternalBlob],
        [ListingId],
        [],
      ),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getBrowseFeed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisplayName' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getInterestedBuyers' : IDL.Func(
        [ListingId],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getMyInterests' : IDL.Func([], [IDL.Vec(ListingId)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isListingSwipedByCaller' : IDL.Func([ListingId], [IDL.Bool], ['query']),
    'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'markListingAsSold' : IDL.Func([ListingId], [], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'resetUsers' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'swipeRightOnListing' : IDL.Func([ListingId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };