/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Condition = { 'good' : null } |
  { 'mint' : null } |
  { 'poor' : null } |
  { 'nearMint' : null } |
  { 'excellent' : null };
export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : ListingId,
  'cardName' : string,
  'isSold' : boolean,
  'seller' : Principal,
  'image' : ExternalBlob,
  'cardSet' : string,
  'priceCents' : PriceCents,
  'sellerUsername' : string,
  'condition' : Condition,
}
export type ListingId = bigint;
export type PriceCents = bigint;
export interface UserProfile { 'username' : Username }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, string, Condition, PriceCents, ExternalBlob],
    ListingId
  >,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getBrowseFeed' : ActorMethod<[bigint, bigint], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDisplayName' : ActorMethod<[Principal], [] | [string]>,
  'getInterestedBuyers' : ActorMethod<[ListingId], Array<[Principal, string]>>,
  'getMyInterests' : ActorMethod<[], Array<ListingId>>,
  'getMyListings' : ActorMethod<[], Array<Listing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isListingSwipedByCaller' : ActorMethod<[ListingId], boolean>,
  'isUserRegistered' : ActorMethod<[], boolean>,
  'markListingAsSold' : ActorMethod<[ListingId], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'resetUsers' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'swipeRightOnListing' : ActorMethod<[ListingId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];